# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: products-orders-management
metadata:
    template: azd-init@1.17.2
services:
    productsservice:
        project: ProductsService
        host: containerapp
        language: dotnet
        docker:
            path: ./ProductsService/Dockerfile
            image: ${AZURE_CONTAINER_REGISTRY_NAME}.azurecr.io/productsservice:latest
            build:
              args:
                BUILD_CONFIGURATION: Release
              tags:
                - latest
        dapr:
            enabled: true
            components-path: ./components/azure
resources:
    productsservice:
        type: host.containerapp
        port: 8080
