version: '3.8'

services:
  #################################
  # Products Service + Dapr sidecar
  #################################
  productsservice:
    build:
      context: ./ProductsService
      dockerfile: Dockerfile
    container_name: productsservice
    ports:
      - "8080:8080"  # productsservice's exposed port
    networks:
      - dapr-net

  dapr-products:
    image: "daprio/daprd:latest"
    container_name: dapr-products
    depends_on:
      - productsservice
      - redis
    restart: on-failure
    command: [
      "/daprd",
      "-app-id", "productsservice",
      "-app-port", "8080",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-components-path", "/components"
    ]
    volumes:
      - ./components:/components
    network_mode: "service:productsservice"

  ######################################################
  # Redis Service (for local pub/sub over Redis Streams)
  ######################################################
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dapr-net

networks:
  dapr-net: